import { Injectable, Input } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { User } from '../models/user.model';
import { Router } from '@angular/router';
import { BehaviorSubject, Observable } from 'rxjs';
import {NgxSpinnerService} from 'ngx-spinner';

/**
 * Handles all authentication related logic.
 *
 * Check: https://jasonwatmore.com/post/2019/06/10/angular-8-user-registration-and-login-example-tutorial
 * see: https://stackoverflow.com/questions/48119369/wait-for-http-request-to-complete-in-angular-4-service
 */
@Injectable()
export class AuthService {

  private currentUserSubject: BehaviorSubject<User>;
  public currentUser: Observable<User>;

  private currentTokenSubject: BehaviorSubject<string>;
  public currentToken: Observable<string>;

  constructor( private http: HttpClient, private router: Router, private spinner: NgxSpinnerService) {
    this.currentTokenSubject = new BehaviorSubject<string>(sessionStorage.getItem('auth_token'));
    this.currentToken = this.currentTokenSubject.asObservable();

    this.currentUserSubject = new BehaviorSubject<User>(JSON.parse(sessionStorage.getItem('auth_user')));
    this.currentUser = this.currentUserSubject.asObservable();
  }

  public get currentUserValue(): User {
    return this.currentUserSubject.value;
  }

  /**
   * Default login method which will authenticate the user based on the given credentials.
   * If the credentials are correct a jwt token will be generated by te api and will be stored in the sessionStorage.
   *
   * @param username
   * @param password
   * @param persist
   */
  public login(username: string, password: string, persist: boolean) {
    return this.http.post<any>('/authenticate',
      {username, password, persist})
      .toPromise()
      .then( res => {
        if (res.jwt) {
          sessionStorage.setItem('auth_token', res.jwt);
          this.currentTokenSubject.next(res.jwt);
          if (persist) {
            localStorage.setItem('auth_token', res.jwt);
          }
        }
      }).catch(err => {
        this.logout();
        console.log(err);
        // Handled by HTTP interceptor: ErrorInterceptor
      });
  }

  /**
   * Will retrieve user data and set it in session storage.
   */
  public whoami() {
    return this.http.get<any>('/whoami')
      .toPromise()
      .then(res => {
        if (res.id) {
          const user = new User(res.id);
          user.name = res.name;
          user.middleName = res.middleName;
          user.lastName = res.lastName;
          user.username = res.username;
          user.email = res.email;
          user.admin = res.admin;
          sessionStorage.setItem('auth_user', JSON.stringify(user));
          this.currentUserSubject.next(user);
        }
      }).catch(err => {
        this.logout();
        console.log(err);
        // Handled by HTTP interceptor: ErrorInterceptor
      });
  }

  /**
   * Destroys the active session and persistent session.
   */
  public logout() {
    this.spinner.show();
    sessionStorage.clear();
    localStorage.clear();
    this.currentUserSubject.next(null);
    this.currentTokenSubject.next(null);
    this.router.navigate(['login']).finally(() => this.spinner.hide());
  }

  /**
   * Check if the user already haves a token in localstorage (persistent login) and uses
   * that token to login into their account.
   */
  public persistLogin() {
    const token = localStorage.getItem('auth_token');
    if (token) {
      sessionStorage.setItem('auth_token', token);
      return true;
    }
    return false;
  }

  /**
   * generates a random password.
   */
  public getGeneratedPassword(length = 10): string {
    const charset = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    return Array(length).fill(length).map(() => charset.charAt(Math.random() * 62)).join('');
  }
}
